# Generated by Django 5.2.4 on 2025-07-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='quantity_sold',
            new_name='quantity',
        ),
    ]
